# Generated by Django 5.1.6 on 2025-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_pics/'),
        ),
    ]
