# Generated by Django 5.1.6 on 2025-03-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_story_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
